version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

workflows:
  version: 2
  build-workflow:
    jobs:
      - build