version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-and-clean:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Remove all files
          command: |
            ls -la
            rm -rf ./* ./.*
            ls -la

workflows:
  version: 2
  build-clean-workflow:
    jobs:
      - build-and-clean